package gcp

import (
	"bytes"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"io/ioutil"
	"os"
	"time"

	"github.com/lestrrat/go-pdebug"

	"google.golang.org/api/compute/v1"
)

func NewCertificateUpload(s *compute.Service, projectID string) *CertificateUpload {
	return &CertificateUpload{
		Project: projectID,
		Service: s,
	}
}

func (cu *CertificateUpload) Upload(name string, certs []*x509.Certificate, certkey *rsa.PrivateKey) (err error) {
	if pdebug.Enabled {
		g := pdebug.Marker("CertificateUpload.Upload (%s)", name).BindError(&err)
		defer g.End()
	}

	// First, save to a local file
	dst, err := ioutil.TempFile("", "gcp-cert-upload-")
	if err != nil {
		return err
	}
	defer os.Remove(dst.Name())
	defer dst.Close()

	for _, cert := range certs {
		if err := pem.Encode(dst, &pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw}); err != nil {
			return err
		}
	}

	if err := dst.Sync(); err != nil {
		return err
	}

	buf := bytes.Buffer{}
	if err := pem.Encode(&buf, &pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(certkey)}); err != nil {
		return err
	}

	sslcert := compute.SslCertificate{
		Certificate: dst.Name(),
		Description: "Certificate generated by Let's Encrypt, uploaded by go-cloud-acmeagent",
		Name:        name,
		PrivateKey:  buf.String(),
	}
	oper, err := cu.Service.SslCertificates.Insert(cu.Project, &sslcert).Do()
	if err != nil {
		return err
	}

	// Poll until the operation is done
	timeout := time.After(5 * time.Minute)
	ticker := time.Tick(5 * time.Second)
	for {
		select {
		case <-timeout:
			return errors.New("timed out waiting for certificate upload")
		case <-ticker:
			oper, err = cu.Service.GlobalOperations.Get(cu.Project, oper.Name).Do()
			if err != nil {
				return err
			}
			switch oper.Status {
			case "DONE":
				if oper.Error != nil {
					buf := bytes.Buffer{}
					for i, e := range oper.Error.Errors {
						if i != 0 {
							buf.WriteByte('\n')
						}
						buf.WriteString(e.Message)
					}
					return errors.New(buf.String())
				}
				return nil
			default:
				if pdebug.Enabled {
					pdebug.Printf("Certificates are not ready. waiting...")
				}
				continue
			}
		}
	}

	return errors.New("failed to poll for operation status")
}
